spring:
  application:
    name: eureka-server-2
server:
  port: 8762
eureka:
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    hostname: eureka-dev-2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-dev-1:8761/eureka
