server:
  port: 1021
spring:
  application:
    name: train-jpa
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/traindb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456@grg
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update  #Hibernate ddl auto (create, create-drop, update, validate, none)

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

