spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    hostname: eureka-dev
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  server:
    #    关闭保护机制
    enable-self-preservation: false