spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      cluster-name: shan
server:
  port: 8500

elasticsearch:
  ip: 127.0.0.1
  port: 9300
  pool: 5
  custer:
    name: master
